name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cat "Transactional Memory/Dockerfile" | docker build -o - . > tutorial.tar
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "tutorial.tar"
