name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Transactional\Memory/Dockerfile --tag tm-tutorial:latest -o - . > tutorial.tar
    - name: Upload the image as an artifact	
      uses: ishworkh/docker-image-artifact-upload@v1	
      with:	
        image: "tm-tutorial:latest"
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "tutorial.tar"
